### ISSUE TITLE
Example Config

### ISSUE THREAD

**Issue by gsugambit** [Tecnativa/docker-haproxy-letsencrypt#1]
Would it be possible for you to add example response to your wiki here on github for those of us wanting to use this?

**Comment by gsugambit** [comment]
like an example that shows your container / haproxy/ and a the php server

**Comment by yajo** [comment]
We use [Traefik](http://traefik.io/) nowadays, this project has reduced maintenance.

If somebody wants to submit a PR we can merge it. I hope you understand. Thanks!
