### ISSUE TITLE
The client lacks sufficient authorization :: Account creation on ACMEv1 is disabled

### ISSUE THREAD

**Issue by eliknebel** [Tecnativa/docker-haproxy-letsencrypt#3]
Trying to create new certs now fails:

`The client lacks sufficient authorization :: Account creation on ACMEv1 is disabled. Please upgrade your ACME client to a version that supports ACMEv2 / RFC 8555. See https://community.letsencrypt.org/t/end-of-life-plan-for-acmev1/88430 for details.`

It appears that ACMEv1 registration is no longer available per End of Life Plan for ACMEv1 api endpoints: https://letsencrypt.status.io/pages/maintenance/55957a99e800baa4470002da/5d9f830b1c84d208a53afac3

**Comment by Sicria** [comment]
@bitbldr Did you find a solution to this, if not, did you find an alternative?

**Comment by yajo** [comment]
This project is deprecated. Go check Traefik. :wink:
